logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
      jooq: TRACE

spring:
  jooq:
    sql-dialect: postgres
  r2dbc:
    url: "r2dbc:postgresql://postgres:postgres@localhost:5432/wallet"